version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    build: .
    container_name: al-folio-website
    command: bash -c "
      bundle install
      && bundle exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll